language: php
php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2

env:
 matrix:
   - DB=MYSQL CORE_RELEASE=3.1
   - DB=MYSQL CORE_RELEASE=3.2

before_script:
 - phpenv rehash
 - composer self-update
 - composer install

script:
 - vendor/bin/phpunit tests/
